# Generated by Django 5.0.6 on 2024-07-03 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flashcard",
            name="users",
        ),
        migrations.AddField(
            model_name="flashcard",
            name="invited_users",
            field=models.ManyToManyField(
                related_name="shared_flashcards", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="flashcard",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_flashcards",
                to="users.profile",
            ),
        ),
    ]
