# Generated by Django 5.0.6 on 2024-07-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0003_alter_flashcard_invited_users"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcard",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="shared_flashcards",
                to="users.profile",
            ),
        ),
    ]
