# Generated by Django 5.0.6 on 2024-12-11 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0006_remove_flashcard_owner_flashcardsset_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flashcardsset",
            name="language_variation",
            field=models.CharField(
                choices=[
                    ("1", "Polish --> English"),
                    ("2", "English --> Polish"),
                    ("3", "Polish --> German"),
                    ("4", "German --> Polish"),
                ],
                default="1",
            ),
        ),
        migrations.CreateModel(
            name="Points",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("positive_answers", models.IntegerField(default=0)),
                ("total_answers", models.IntegerField(default=0)),
                (
                    "flashcards_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="points",
                        to="flashcards.flashcardsset",
                    ),
                ),
            ],
        ),
    ]
