# Generated by Django 5.0.6 on 2025-01-15 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0007_alter_flashcardsset_language_variation_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="points",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
